### ISSUE TITLE
.gitignore not working properly

### ISSUE THREAD

**Issue by spdvi** [KrilianAlpha/SPDVI_DI_O1Task#2]
There a lot of unnecessary files in the repository.
Althought there is a .gitignore, it is not working in the remote.

**Comment by KrilianAlpha** [comment]
That's weird, I checked and put the visual studio version. I Will chance It nos either way, and check if that works

**Comment by KrilianAlpha** [comment]
I change it, don't know if it works now

**Comment by spdvi** [comment]
NO. bin/Debug, /obj/Debug, .vs/... still are in github.

**Comment by KrilianAlpha** [comment]
okey i found a solution but requires me to delete the files from the repository and add them again

**Comment by spdvi** [comment]
There's a better solution. But as soon as you achieve the desired result without corrupting the git commit history all are fine!

**Comment by KrilianAlpha** [comment]
Ok, It should be done

**Comment by spdvi** [comment]
Yep, that's good now ^^
