### ISSUE TITLE
Missing procedure

### ISSUE THREAD

**Issue by spdvi** [KrilianAlpha/SPDVI_DI_O1Task#3]
App throws an exception in initialization:
- Could not find stored procedure 'dbo.getProductPages' when running in local database.
That procedure is not included in the StoredProcedures.sql files.

**Comment by KrilianAlpha** [comment]
working on it

**Comment by KrilianAlpha** [comment]
It should be fixed now

**Comment by spdvi** [comment]
It is but now it complains about dbo.getProductLine

**Comment by KrilianAlpha** [comment]
Checking

**Comment by KrilianAlpha** [comment]
done

**Comment by spdvi** [comment]
Thanks, all good now.
